# Generated by Django 4.2.1 on 2024-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_login', '0002_alter_tokens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='user',
            field=models.CharField(db_column='phoneNumber', max_length=20, verbose_name='شماره تماس'),
        ),
    ]
