# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='نام صفحه برند های سایت')),
            ],
            options={
                'verbose_name': 'صفحه آرشیو برند ها',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='BrandPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.CharField(max_length=300, verbose_name='کلید واژه برند')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات کامل برند')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها ',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
    ]
