# Generated by Django 4.2.1 on 2023-06-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('brand', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='تصویر شاخص برند را اضافه کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='تصویر شاخص برند'),
        ),
    ]
