# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('index', '0001_initial'),
        ('category', '0002_initial'),
        ('brand', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('shenase', models.CharField(max_length=300, verbose_name='شناسه محصول')),
                ('product_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام و مدل محصول')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه محصول')),
                ('description', wagtail.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='درباره محصول')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='تعداد محصول')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post date')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('short_description', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('product_type', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='نوع محصول')),
                ('product_jense', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='جنس محصول')),
                ('product_wight', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='وزن محصول')),
                ('product_abad', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='ابعاد خارجی محصول')),
                ('product_size', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='سایز محصول')),
                ('product_garr', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='گارانتی محصول')),
                ('total_visits', models.IntegerField(default=0, verbose_name='تعداد کل بازدید')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(help_text='یک برند برای محصول انتخاب کنید', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='brand.brandpage', verbose_name='برند محصول')),
                ('collection', models.ForeignKey(blank=True, help_text='مجموعه برای محصول انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categoryproduct')),
                ('comments', models.ManyToManyField(blank=True, to='index.comments')),
                ('image', models.ForeignKey(help_text='تصویر شاخص محصول را اضافه کنید', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='تصویر شاخص محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='نام صفحه محصولات سایت')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیجات')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه صفحه محصولات')),
            ],
            options={
                'verbose_name': 'صفحه محصولات',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProductSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('slide_title', models.CharField(db_index=True, max_length=14, verbose_name='عنوان اسلاید')),
                ('slide_desc', models.CharField(blank=True, max_length=35, null=True, verbose_name='توضیحات')),
                ('collection', models.ForeignKey(blank=True, help_text='مجموعه برای رنگ بندی انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
                ('image', models.ForeignKey(help_text='تصویر اسلاید را وارد نمایید', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='تصویر اسلاید')),
                ('product_slide', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_SLIDE', to='product.inventoryitem')),
            ],
            options={
                'verbose_name': 'اسلاید تصاویر محصول',
                'verbose_name_plural': 'اسلاید تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('offer_title', models.CharField(db_index=True, max_length=14, verbose_name='عنوان تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='قیمت جدید محصول')),
                ('offer_des', models.CharField(blank=True, max_length=35, null=True, verbose_name='توضیحات تخفیف')),
                ('collection', models.ForeignKey(blank=True, help_text='مجموعه برای تخفیف انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
                ('product_offer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_OFFER', to='product.inventoryitem')),
            ],
            options={
                'verbose_name': 'محصول تخفیف دار',
                'verbose_name_plural': 'محصولات تخفیف دار',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color_title', models.CharField(db_index=True, max_length=14, verbose_name='نام رنگ بندی')),
                ('color', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('pquantity', models.IntegerField(verbose_name='تعداد رنگ بندی :')),
                ('color_des', models.CharField(blank=True, max_length=35, null=True, verbose_name='توضیحات')),
                ('collection', models.ForeignKey(blank=True, help_text='مجموعه برای رنگ بندی انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
                ('product_color', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_COLORS', to='product.inventoryitem')),
            ],
            options={
                'verbose_name': 'رنگ بندی',
                'verbose_name_plural': 'رنگ بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.inventoryitem')),
            ],
            options={
                'verbose_name': 'انبار کالا',
                'verbose_name_plural': 'انبار کالا',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('dis_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'ثابت')], max_length=20, verbose_name='نوع اعمال تخفیف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('collection', models.ForeignKey(blank=True, help_text='انتخاب دسته بندی برای اعمال کد تخفیف', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categoryproduct')),
                ('product', models.ForeignKey(blank=True, help_text='انتخاب محصول برای اعمال کد تخفیف', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.inventoryitem')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
    ]
