# Generated by Django 4.2.1 on 2023-07-04 06:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_categoryblog_image_categoryproduct_image'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='collection',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='collection',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='مجموعه برای محصول انتخاب کنید', null=True, to='category.categoryproduct'),
        ),
    ]
