# Generated by Django 4.2.1 on 2023-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_inventoryitem_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenase', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='شناسه سفارش')),
                ('customer', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='مشتری')),
                ('product', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='محصول')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('color', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='رنگ')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('status', models.IntegerField(choices=[(0, 'در حال پردازش'), (1, 'تکمیل شده'), (2, 'استرداد'), (3, 'لغو شده'), (4, 'در انتظار پرداخت')], default=0, verbose_name='وضعیت سفارش')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('send_method', models.IntegerField(choices=[(0, 'تحویل حضوری'), (1, 'پست پیشتاز'), (2, 'پیک')], default=0, verbose_name='روش ارسال')),
                ('send_price', models.PositiveIntegerField(verbose_name='هزینه ارسال')),
            ],
            options={
                'verbose_name': 'سفارش ثبت شده',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ['-date'],
            },
        ),
    ]
