# Generated by Django 4.2.1 on 2023-07-11 13:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
