# Generated by Django 4.2.1 on 2023-07-12 06:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_inventoryitem_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=320, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
