# Generated by Django 4.2.1 on 2024-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_inventoryitem_short_description'),
    ]

    operations = [
    ]
