# Generated by Django 4.2.1 on 2024-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20240506_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_note',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='یاداشت سفارش'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='send_method',
            field=models.IntegerField(choices=[(0, 'تیپاکس پس کرایه ای'), (1, 'پست ویژه'), (2, 'پیک پس کرایه ای')], default=0, verbose_name='روش ارسال'),
        ),
    ]
