# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='نام صفحه دسته بندی های سایت')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیجات')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه صفحه دسته بندی ها')),
            ],
            options={
                'verbose_name': 'صفحه آرشیو دسته بندی ها',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه دسته بندی محصول')),
                ('description', models.CharField(max_length=60, verbose_name='توضیحات کامل دسته بندی')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, help_text='یک مجموعه برای دسته بندی محصول انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه دسته بندی مقاله')),
                ('description', models.CharField(max_length=60, verbose_name='توضیحات کامل دسته بندی')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, help_text='یک مجموعه برای دسته بندی مقاله انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
            ],
            options={
                'verbose_name': 'دسته بندی وبلاگ',
                'verbose_name_plural': 'دسته بندی های وبلاگ',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
    ]
