# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('index', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='نام صفحه وبلاگ سایت')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیجات')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه صفحه بلاگ')),
            ],
            options={
                'verbose_name': 'صفحه اصلی وبلاگ',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیجات')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه مقاله')),
                ('intro', models.CharField(max_length=25, verbose_name='توضیحات ابتدایی راجب پست')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post date')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='محتوای پست')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(help_text='یک دسته بندی انتخاب کنید', on_delete=django.db.models.deletion.PROTECT, to='category.categoryblog')),
                ('comments', models.ManyToManyField(blank=True, to='index.comments')),
                ('image', models.ForeignKey(help_text='یک تصویر بارگزاری کنید', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='تصویر شاخص پست')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست های وبلاگ',
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
    ]
