# Generated by Django 4.2.1 on 2023-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='is_supporter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='عضو تیم پشتیبانی'),
        ),
    ]
