# Generated by Django 4.2.1 on 2023-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_user_accounts_is_supporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'اطلاعات مشتریان'},
        ),
        migrations.AddField(
            model_name='customer',
            name='code_melli',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='static_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
