# Generated by Django 4.2.1 on 2023-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_customer_options_customer_code_melli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='fadax_payment_possible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='امکان پرداخت فدکس برای کاربر'),
        ),
    ]
