# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=25, null=True, verbose_name='کاربر نظر دهنده')),
                ('post', models.CharField(blank=True, max_length=25, null=True, verbose_name='پست')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان نظر')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام نظر دهنده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل نظر دهنده')),
                ('body', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت نظر')),
            ],
            options={
                'verbose_name': 'بازخورد کاربر',
                'verbose_name_plural': 'بازخورد کاربران',
            },
        ),
        migrations.CreateModel(
            name='Comments_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=25, null=True, verbose_name='کاربر لایک / دیسلایک کننده')),
                ('post', models.CharField(blank=True, max_length=25, null=True, verbose_name='پست لایک/ دیسلایک شده')),
                ('like', models.PositiveIntegerField(blank=True, null=True, verbose_name='مجموع لایک پست')),
                ('dis_like', models.PositiveIntegerField(blank=True, null=True, verbose_name='مجموع دیسلایک پست')),
            ],
            options={
                'verbose_name': 'لایک و دیسلایک',
                'verbose_name_plural': 'لایک ها و دیسلایک ها',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیجات')),
                ('keywords', models.TextField(blank=True, db_index=True, null=True, verbose_name='کلید واژه صفحه اصلی')),
            ],
            options={
                'verbose_name': 'خانه',
            },
            bases=('wagtailcore.page',),
        ),
    ]
