# Generated by Django 4.2.1 on 2023-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='جمع بازدید')),
                ('last_visit_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='آخرین آدرس بازدید شده')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آیپی')),
                ('session_key', models.GenericIPAddressField(blank=True, null=True, verbose_name='کلید نشست')),
                ('browser', models.CharField(blank=True, max_length=200, null=True, verbose_name='مروگر')),
                ('browser_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='نسخه مرورگر')),
                ('os', models.CharField(blank=True, max_length=200, null=True, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='نسخه سیستم عامل')),
                ('device', models.CharField(blank=True, max_length=200, null=True, verbose_name='دستگاه')),
                ('last_visit_time', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین سابقه بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'آمار بازدید',
            },
        ),
    ]
