# Generated by Django 4.2.1 on 2023-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='visit',
            name='country_emoji',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='نماد کشور'),
        ),
        migrations.AddField(
            model_name='visit',
            name='current_time',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='زمان فعلی'),
        ),
        migrations.AddField(
            model_name='visit',
            name='isp',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='سرویس دهنده'),
        ),
        migrations.AddField(
            model_name='visit',
            name='zip_code',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='کد پستی'),
        ),
    ]
