# Generated by Django 4.2.1 on 2023-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_visit_city_visit_country_visit_country_emoji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان صفحه')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='آدرس صفحه')),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='توضیحات')),
                ('keywords', models.CharField(max_length=50, unique=True, verbose_name='کلیدواژه ها')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('status', models.IntegerField(choices=[(0, 'پیش نویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحه ها',
                'ordering': ['-created_on'],
            },
        ),
    ]
