# Generated by Django 4.2.1 on 2023-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه محصول')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محصول')),
                ('product_collection', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دسته بندی محصول')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='تعداد محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='تصویر محصول')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ محصول')),
                ('color_quantity', models.PositiveIntegerField(null=True, verbose_name='تعداد رنگ بندی موجود')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر')),
                ('product_id1', models.CharField(blank=True, max_length=100, null=True, verbose_name='۱شناسه محصول')),
                ('product_id2', models.CharField(blank=True, max_length=100, null=True, verbose_name='۲شناسه محصول')),
                ('product_title1', models.CharField(blank=True, max_length=100, null=True, verbose_name='۱نام محصول')),
                ('product_title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='۲نام محصول')),
                ('product_collection1', models.CharField(blank=True, max_length=100, null=True, verbose_name='۱شناسه دسته بندی محصول')),
                ('product_collection2', models.CharField(blank=True, max_length=100, null=True, verbose_name='۲شناسه دسته بندی محصول')),
                ('quantity1', models.PositiveIntegerField(null=True, verbose_name='تعداد محصول۱')),
                ('quantity2', models.PositiveIntegerField(null=True, verbose_name='تعداد محصول۲')),
                ('price1', models.PositiveIntegerField(null=True, verbose_name='قیمت۱')),
                ('price2', models.PositiveIntegerField(null=True, verbose_name='قیمت۲')),
                ('image1', models.CharField(blank=True, max_length=100, null=True, verbose_name='۱تصویر محصول')),
                ('image2', models.CharField(blank=True, max_length=100, null=True, verbose_name='۲تصویر محصول')),
                ('color1', models.CharField(blank=True, max_length=30, null=True, verbose_name='۱رنگ محصول')),
                ('color2', models.CharField(blank=True, max_length=30, null=True, verbose_name='۲رنگ محصول')),
                ('brand1', models.CharField(blank=True, max_length=30, null=True, verbose_name='۱برند محصول')),
                ('brand2', models.CharField(blank=True, max_length=30, null=True, verbose_name='۲برند محصول')),
                ('color_quantity1', models.PositiveIntegerField(null=True, verbose_name='۱تعداد رنگ بندی موجود')),
                ('color_quantity2', models.PositiveIntegerField(null=True, verbose_name='۲تعداد رنگ بندی موجود')),
                ('product_type1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='نوع محصول۱')),
                ('product_type2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='نوع محصول۲')),
                ('product_jense1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='جنس محصول۱')),
                ('product_jense2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='جنس محصول۲')),
                ('product_wight1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='وزن محصول۱')),
                ('product_wight2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='وزن محصول۲')),
                ('product_abad1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='ابعاد خارجی محصول۱')),
                ('product_abad2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='ابعاد خارجی محصول۲')),
                ('product_size1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='سایز محصول۱')),
                ('product_size2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='سایز محصول۲')),
                ('product_garr1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='گارانتی محصول۱')),
                ('product_garr2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='گارانتی محصول۲')),
                ('slug1', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='اسلاگ محصول اول')),
                ('slug2', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='اسلاگ محصول دوم')),
            ],
            options={
                'verbose_name': 'مقایسه محصول',
                'verbose_name_plural': 'مقایسات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه محصول')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محصول')),
                ('product_collection', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دسته بندی محصول')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='تعداد محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='تصویر محصول')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ محصول')),
                ('color_quantity', models.PositiveIntegerField(null=True, verbose_name='تعداد رنگ بندی موجود')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='اسلاگ محصول')),
            ],
            options={
                'verbose_name': 'علاقه مندی کاربر ',
                'verbose_name_plural': 'علاقه مندی های کاربران',
            },
        ),
    ]
