# Generated by Django 4.2.1 on 2023-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='اتاق')),
                ('support_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('support_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت پشتیبانی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'پشتیبانی کاربر',
                'verbose_name_plural': 'پشتیبانی کاربران',
            },
        ),
    ]
