# Generated by Django 4.2.1 on 2023-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_supportrequest_alter_support_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='جمع کل'),
        ),
    ]
