# Generated by Django 4.2.1 on 2023-09-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_support_time'),
    ]

    operations = [
    ]
