# Generated by Django 4.2.1 on 2023-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20230917_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fadax_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره سفارش')),
                ('customer', models.CharField(blank=True, max_length=30, null=True, verbose_name='مشتری')),
                ('refId', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره ارجاع')),
                ('fadaxTrackingId', models.CharField(blank=True, max_length=30, null=True, verbose_name='شناسه ارجاع فدکس')),
                ('fadaxTrackingNumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تراکنش فدکس')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='وضعیت تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش فدکس',
                'verbose_name_plural': 'تراکنش های فدکس',
            },
        ),
    ]
