# Generated by Django 4.2.1 on 2023-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_fadax_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fadax_payment',
            name='paymentToken',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='وضعیت تراکنش'),
        ),
    ]
