# Generated by Django 4.2.1 on 2024-04-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_fadax_payment_paymenttoken'),
    ]

    operations = [
    ]
