# Generated by Django 4.2.1 on 2024-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20240428_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='cart',
            name='offer_code_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ کد تخفیف'),
        ),
    ]
